name: Build

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Init
        run: |
          sudo apt install cmake ninja-build pkg-config clang clang-format build-essential curl ccache git zsh
          sudo apt install libavcodec-dev libavdevice-dev libavfilter-dev libavformat-dev libavutil-dev libswresample-dev libswscale-dev libx264-dev libcurl4-openssl-dev libmbedtls-dev libgl1-mesa-dev libjansson-dev libluajit-5.1-dev python3-dev libx11-dev libxcb-randr0-dev libxcb-shm0-dev libxcb-xinerama0-dev libxcb-composite0-dev libxcomposite-dev libxinerama-dev libxcb1-dev libx11-xcb-dev libxcb-xfixes0-dev swig libcmocka-dev libxss-dev libglvnd-dev libgles2-mesa libgles2-mesa-dev libwayland-dev libsrt-openssl-dev libpci-dev libpipewire-0.3-dev libqrcodegencpp-dev uthash-dev
          sudo apt install qt6-base-dev qt6-base-private-dev libqt6svg6-dev qt6-wayland qt6-image-formats-plugins
          sudo apt install \
             libasound2-dev \
             libfdk-aac-dev \
             libfontconfig-dev \
             libfreetype6-dev \
             libjack-jackd2-dev \
             libpulse-dev libsndio-dev \
             libspeexdsp-dev \
             libudev-dev \
             libv4l-dev \
             libva-dev \
             libvlc-dev \
             libvpl-dev \
             libdrm-dev \
             nlohmann-json3-dev \
             libwebsocketpp-dev \
             libasio-dev
      - name: Build
        run: |
          wget https://cdn-fastly.obsproject.com/downloads/cef_binary_5060_linux_x86_64_v3.tar.xz
          tar -xf ./cef_binary_5060_linux_x86_64_v3.tar.xz
          git clone --recursive https://github.com/obsproject/obs-studio.git -b 29.1.3
          cd obs-studio
          mkdir build && cd build
          cmake -DLINUX_PORTABLE=ON -DCMAKE_INSTALL_PREFIX="${HOME}/obs-studio-portable" -DENABLE_BROWSER=ON -DCEF_ROOT_DIR="../../cef_binary_5060_linux_x86_64" -DENABLE_AJA=OFF -DENABLE_NEW_MPEGTS_OUTPUT=OFF ..
          make -j4 && make install
      - uses: actions/upload-artifact@v4
        with:
          name: obs
          path: ~/obs-studio-portable
